---
dataset:
  type: MNIST
  params_train:
    batch_size: 64
    train: True
    num_workers: 0
    # n_malicious: 2
    # shrink: 0.2
  params_test:
    batch_size: 1000
    train: False
    num_workers: 0
model:
  type: ReLuMLP
  params:
    layers: [784, 500, 500, 10]
optimizer:
  type: SGD
  params:
    lr: 0.01
    momentum: 0.9
loss_fn:
  type: CrossEntropyLoss
  params:
training:
  # seed: 0
  use_gpu: False
  n_epochs: 1 # 20
  max_buffer_len: 16
  shuffle_batches: False
  log_dir: times_test #_queue_nowait #async_manager #freivalds_async_cpu_disk
  training_method: no_attack
  training_params: {}
  # training_method: targeted_attack
  # training_params:
  #   boosting: True
  #   boost_factor: 50
  # training_method: untargeted_attack
  # training_params:
  #   frequency: 0.1
  #   scale: 0.25
validation:
  run_validation: True
  async_validators: 1
  async_disk_queue: False
  validation_type: extract
  validation_method: freivald # submul # gvfa # freivald # matmul
  verbose: False
  silent: True
  # n_check: 9
  guarantee: 0.99
  validation_delay: 3
  monitor_memory: True
  # val_prob: 0
